site_name: Python app using Podman

nav:
  - Introduction : index.md
  - Setup: setup.md
  - Create Web App : create-web-app.md
  - Create Docker File : create-dockerfile.md
  - Create Image : create-image.md
  - Run your App : run-your-app.md
  - Cleanup : cleanup.md
theme: readthedocs